services:
  fastapi-app:
    build: ./app
    container_name: fastapi-app
    expose:
      - "3000"
    environment:
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
    #networks:
    #  - app-network
    restart: unless-stopped

  cloudpub:
    image: cloudpub/cloudpub:latest
    container_name: cloudpub-tunnel
    restart: unless-stopped
    environment:
      - TOKEN=${CLOUDPUB_TOKEN}
      - HTTP=fastapi-app:3000
    command: run
    depends_on:
      - fastapi-app
    volumes:
      - cloudpub-config:/home/cloudpub

volumes:
  cloudpub-config:

#networks:
  #app-network:
    #driver: bridge